name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build
        run: |
          pnpm build:components

      - name: Create Release Pull Request
        id: create_release
        # uses: changesets/action@v1
        # with:
        #   tagName: ${{ env.VERSION }}
        #   releaseName: '${{ env.VERSION }}'
        #   publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ "$TAG_NAME" == *beta* ]];then
            echo "发布beta版本"
            pnpm ci:beta
          else:
            echo "发布release版本"
            pnpm ci:publish
          fi
